# Generated by Django 5.2 on 2025-10-01 00:00
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('responsavel', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={'verbose_name': 'Secretaria', 'verbose_name_plural': 'Secretarias', 'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='sAMAccountName ou UPN do AD', max_length=80, unique=True)),
                ('nome', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=160, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('origem_ad', models.BooleanField(default=True, help_text='Marca se veio do AD')),
            ],
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários', 'ordering': ['username']},
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=120)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carros', to='frotas.secretaria')),
            ],
            options={'verbose_name': 'Carro', 'verbose_name_plural': 'Carros', 'ordering': ['placa']},
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_saida', models.DateTimeField()),
                ('odometro_saida', models.PositiveIntegerField()),
                ('data_chegada', models.DateTimeField(blank=True, null=True)),
                ('odometro_chegada', models.PositiveIntegerField(blank=True, null=True)),
                ('destino', models.CharField(max_length=160)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('carro', models.ForeignKey(db_column='carro_placa', on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='frotas.carro', to_field='placa')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='frotas.usuario')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='frotas.secretaria')),
            ],
            options={'verbose_name': 'Viagem', 'verbose_name_plural': 'Viagens', 'ordering': ['-data_saida']},
        ),
    ]
