# Generated by manual squash to remove legacy AD references
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    # This squashes the initial migration set into a clean state without any AD-related fields
    replaces = [
        ('frotas', '0001_initial'),
        ('frotas', '0002_add_odometro_atual'),
        ('frotas', '0003_make_odometro_nullable'),
        ('frotas', '0004_usuario_somente_nome'),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('responsavel', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=120)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('odometro_atual', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carros', to='frotas.secretaria')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_saida', models.DateTimeField()),
                ('odometro_saida', models.PositiveIntegerField()),
                ('data_chegada', models.DateTimeField(blank=True, null=True)),
                ('odometro_chegada', models.PositiveIntegerField(blank=True, null=True)),
                ('destino', models.CharField(max_length=160)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('carro', models.ForeignKey(db_column='carro_placa', on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='frotas.carro', to_field='placa')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='frotas.usuario')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='frotas.secretaria')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['-data_saida'],
            },
        ),
    ]
