# Generated by Django 5.2.6 on 2025-10-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frotas', '0007_viagem_motorista_fk'),
    ]

    # No-op: o modelo 'Usuario' foi renomeado para 'Motorista' em 0006,
    # então esta migration não deve tentar removê-lo.
    operations = []
