# Generated by Django 5.2.6 on 2025-10-05 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frotas', '0008_delete_usuario_alter_viagem_carro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='carro',
            field=models.ForeignKey(db_column='carro_placa', on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='frotas.carro'),
        ),
    ]
