# Generated by Django 5.2.6 on 2025-10-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frotas', '0009_alter_viagem_carro_alter_motorista_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='motorista',
            table='frotas_motorista',
        ),
    ]
