# Generated by Django 5.2.6 on 2025-10-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frotas', '0010_rename_usuario_table_to_motorista'),
    ]

    operations = []
