# Generated by Django 5.2 on 2025-10-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frotas', '0011_alter_viagem_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='em_andamento', max_length=20),
        ),
    ]
