# Generated by Django 5.2 on 2025-10-06 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frotas', '0012_viagem_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No-op: tabela já existe no banco (evita erro 1050 Table already exists)
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Localizacao',
                    fields=[
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('atualizado_em', models.DateTimeField(auto_now=True)),
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('nome', models.CharField(max_length=160)),
                        ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                        ('descricao', models.TextField(blank=True, null=True)),
                        ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                        ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                    ],
                    options={
                        'verbose_name': 'Localização',
                        'verbose_name_plural': 'Localizações',
                        'ordering': ['nome'],
                    },
                ),
            ],
        ),
        migrations.AddField(
            model_name='viagem',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='frotas.localizacao'),
        ),
    ]
