# Generated by Django 5.2 on 2025-10-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frotas', '0013_localizacao_viagem_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='sem_placa',
            field=models.BooleanField(default=False, help_text='Marque quando o veículo não possuir placa (gera identificador interno).'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
