# Generated by Django 5.2 on 2025-10-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frotas', '0014_carro_sem_placa_alter_carro_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='tem_odometro',
            field=models.BooleanField(default=True, help_text='Marque se o veículo possui odômetro.'),
        ),
    ]
