# Generated by Django 5.2 on 2025-10-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frotas', '0015_carro_tem_odometro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='odometro_saida',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
